CREATE TABLE TWSS_CLOTHING_TYPES(
	ID NUMBER NOT NULL,
    NAME VARCHAR2(250 BYTE) NOT NULL,
    CONSTRAINT TWSS_CT_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_CT_UQ UNIQUE (NAME)
);

CREATE TABLE TWSS_CLOTHING_CATEGORIES(
	ID NUMBER NOT NULL,
    NAME VARCHAR2(250 BYTE) NOT NULL,
    CONSTRAINT TWSS_CC_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_CC_UQ UNIQUE (NAME)
);

CREATE TABLE TWSS_BRANDS(
	ID NUMBER NOT NULL,
    NAME VARCHAR2(250 BYTE) NOT NULL,
    CONSTRAINT TWSS_BRANDS_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_BRD_NAME_UQ UNIQUE (NAME)
);

---------------------------------------------------------------------
 
CREATE TABLE TWSS_CLOTHES(
    ID NUMBER NOT NULL,
    UUID VARCHAR2(250 BYTE) NOT NULL,
    USERNAME VARCHAR2(250 BYTE) NOT NULL,
    NAME VARCHAR2(250 BYTE) NOT NULL,
    DESCRIPTION VARCHAR2(250 BYTE) NULL,
    TYPE VARCHAR2(250 BYTE) NOT NULL,
    CATEGORY VARCHAR2(250 BYTE) NOT NULL,
    PURCHASE_DATE DATE NULL,
    HOW_LIKE NUMBER NULL,
    BRAND VARCHAR2(250 BYTE) NULL,
    STATE NUMBER(1) DEFAULT (1) NOT NULL,
    COLOR_CODE VARCHAR2(250 BYTE) NOT NULL,
    COLOR_NAME VARCHAR2(250 BYTE) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_CLOTHES_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_CLOTHES_UUID_UQ UNIQUE (UUID)
);


CREATE SEQUENCE TWSS_CLOTHES_SEQ;
 
CREATE TRIGGER TWSS_CLOTHES_TRG
BEFORE INSERT ON TWSS_CLOTHES
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_CLOTHES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/