Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (1,'BLANCO','FFFFFF');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (2,'AMARILLO','FFC30F');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (3,'AZUL','038cb8');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (4,'BEIGE','e7e1c1');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (5,'MARRÓN','683b11');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (6,'DORADO','b78e24');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (7,'FUCSIA','f50087');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (8,'GRIS','7c7c7c');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (9,'MORADO','6b1b56');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (10,'NARANJADO','f05d00');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (11,'NEGRO','000000');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (12,'ROJO','e40613');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (13,'ROSADO','f7a4ac');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (14,'VERDE','008000');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (15,'VINO TINTO','5e070d');
Insert into TWSS_BASE_COLORS (ID,NAME,HEXA) values (16,'VIOLETA','8f5ba1');

Insert into TWSS_BRANDS (ID,NAME) values (1,'AMERICACINO');
Insert into TWSS_BRANDS (ID,NAME) values (2,'LEVIS');
Insert into TWSS_BRANDS (ID,NAME) values (3,'BIG JOHN');
Insert into TWSS_BRANDS (ID,NAME) values (4,'RIFLE');
Insert into TWSS_BRANDS (ID,NAME) values (5,'NIKE');

Insert into TWSS_CLOTHING_CATEGORIES (ID,NAME) values (1,'INFORMAL');
Insert into TWSS_CLOTHING_CATEGORIES (ID,NAME) values (2,'FORMAL');
Insert into TWSS_CLOTHING_CATEGORIES (ID,NAME) values (3,'TRABAJO');
Insert into TWSS_CLOTHING_CATEGORIES (ID,NAME) values (4,'DEPORTIVA');

Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (1,'BOXER');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (2,'CAMISETA');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (3,'CAMISA');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (4,'MEDIAS');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (5,'PANTALONES');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (6,'ZAPATOS');
Insert into TWSS_CLOTHING_TYPES (ID,NAME) values (7,'TENIS');

Insert into TWSS_CLOTHES (UUID,USERNAME,NAME,DESCRIPTION,TYPE,CATEGORY,PURCHASE_DATE,HOW_LIKE,BRAND,STATE,COLOR_CODE,BASE_COLOR) values ('3cd24e84-92a6-11e8-9eb6-529269fb1459','julian','CAMISA AZUL OSCURA RIFLE','CAMISA AZUL OSCURA RIFLE COMPRADA EN MARINILLA','CAMISA','INFORMAL',to_date('04-JUL-17','DD-MON-RR'),8,'RIFLE',1,'#081c3d',3);