CREATE TABLE TWSS_CALENDAR_DESCRIPTION(
    ID NUMBER NOT NULL,
    USERNAME VARCHAR2(250 BYTE) NOT NULL,
    DAY DATE NOT NULL,
    DESCRIPTION VARCHAR2(250 BYTE) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_CALENDAR_DESC_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_CALENDAR_DES_UQ UNIQUE (USERNAME, DAY)
);


CREATE SEQUENCE TWSS_CALENDAR_DESC_SEQ;
 
CREATE TRIGGER TWSS_CALENDAR_DESC_TRG
BEFORE INSERT ON TWSS_CALENDAR_DESCRIPTION
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_CALENDAR_DESC_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/